services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HMMH\SolrFileIndexer\:
    resource: '../Classes/*'

  HMMH\SolrFileIndexer\Listener\RemoveFile:
    tags:
      - name: event.listener
        identifier: 'tx-solr-file-indexer-remove-file'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileRemovedFromIndexEvent

  HMMH\SolrFileIndexer\Listener\AddMetadata:
    tags:
      - name: event.listener
        identifier: 'tx-solr-file-indexer-add-metadata'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataCreatedEvent

  HMMH\SolrFileIndexer\Task\ItemQueueWorkerTask:
    tags:
      - name: 'console.command'
        command: 'solr_file_indexer:item-queue-worker'
        schedulable: true
