services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HMMH\SolrFileIndexer\:
    resource: '../Classes/*'

  HMMH\SolrFileIndexer\Listener\RemoveFile:
    tags:
      - name: event.listener
        identifier: 'tx-solr-file-indexer-reove-file'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileRemovedFromIndexEvent
