services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HMMH\SolrFileIndexer\:
    resource: '../Classes/*'

  HMMH\SolrFileIndexer\Middleware\IndexingMiddleware:
    public: true
    autowire: true
    shared: false
    arguments:
      $logger: !service
        class: ApacheSolrForTypo3\Solr\System\Logging\SolrLogManager
        arguments:
          $className: 'HMMH\SolrFileIndexer\Middleware\IndexingMiddleware'

  HMMH\SolrFileIndexer\Task\ItemQueueWorkerTask:
    tags:
      - name: 'console.command'
        command: 'solr_file_indexer:item-queue-worker'
        schedulable: true

  HMMH\SolrFileIndexer\Task\DeleteByTypeTask:
    tags:
      - name: 'console.command'
        command: 'solr_file_indexer:delete-by-type'
        schedulable: true
